# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Production dependencies - triggers semantic releases
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"  # Triggers PATCH release
    open-pull-requests-limit: 5
    ignore:
      # Ignore test dependencies in this update group
      - dependency-name: "org.junit:*"
      - dependency-name: "org.junit.jupiter:*"
      - dependency-name: "org.junit.platform:*"
      - dependency-name: "org.assertj:*"
      - dependency-name: "org.mockito:*"
      - dependency-name: "com.approvaltests:*"
    groups:
      lsd-dependencies:
        patterns:
          - "io.github.lsd-consulting:*"

      kotlin-dependencies:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.dokka*"
        update-types:
          - "minor"
          - "patch"

  # Test dependencies - does not trigger semantic releases
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "test"  # Does not trigger semantic release
    open-pull-requests-limit: 5
    groups:
      junit-dependencies:
        patterns:
          - "org.junit:*"
          - "org.junit.jupiter:*"
          - "org.junit.platform:*"
        update-types:
          - "minor"
          - "patch"

      testing-dependencies:
        patterns:
          - "org.assertj:*"
          - "org.mockito:*"
          - "com.approvaltests:*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"  # For workflow updates - no version impact

