# For an example see: https://github.com/GeekHomeInside/semantic-release-example/blob/master/.releaserc.yaml
branches: [ "main" ]
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"